name: Manual Publish

on:
  workflow_dispatch:

jobs:
  ## PUBLISH ##
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Publish npm package
        env:
          NPM_USER: ${{ secrets.NPM_USER }}
          NPM_PASS: ${{ secrets.NPM_PASS }}
          NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
        run: |
          set -x
          git config --local user.name ${{ secrets.GITHUB_TOKEN }}
          npm install -g npm-cli-login
          npm-cli-login
          npm run release:beta

  ## RELEASE ##
  release:
    name: Release

    needs: publish

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Release
        run: |
        set -x
        git config --local user.name ${{ secrets.GITHUB_TOKEN }}
        npm run release
