name: Manual Publish

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Build
        run: |
          set -x
          npm install
          npm run bootstrap
          npm run build

  ## RELEASE ##
  release:
    name: Release
    needs: publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Pushlish npm package
        env:
          NPM_USER: phonghmh
          NPM_PASS: Hoaiphong2511
          NPM_EMAIL: phong.hoang@katalon.com
        run: |
          set -x
          echo "username: $NPM_USER"
          echo "password: $NPM_PASS"
          echo "email: $NPM_EMAIL"
          npm install -g npm-cli-login
          npm-cli-login
          npm install
          npm run release