name: Test

on:
  pull_request:
    branches:
      - master
      - release

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install, build
        run: |
          set -x
          npm install
          npm run bootstrap
          npm run test