name: Test

on:
  pull_request:
    branches:
      - master
      - release

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install, build
        env:
          TESTOPS_BASE_PATH: ${{ secrets.TESTOPS_BASE_PATH }}
          TESTOPS_API_KEY: ${{ secrets.TESTOPS_API_KEY }}
          TESTOPS_PROJECT_ID: ${{ secrets.TESTOPS_PROJECT_ID }}
        run: |
          set -x
          npm install
          npm run bootstrap
          npm run link
          cd $GITHUB_WORKSPACE/packages/testops-jest
          npm install
          npm test